Toggle option added
torbenkeller/expandable_bottom_sheet pull request #9
Opened 2021-06-06 04:07 UTC by BobanBaby

Toggle option added along with drag

2021-06-06 08:34 UTC, torbenkeller commented
Thanks for the PR!

Before I merge it, could you please do this:
* reformat the code with a line length of 100 
* add an option in the constructor to enable the toggling

2021-06-06 10:04 UTC, BobanBaby commented
Done !


Made some changes according to pedantic/analysis_options.yaml. Please do check those also

2021-06-07 21:01 UTC, torbenkeller requested changes

2021-06-07 21:01 UTC, torbenkeller commented on lib/src/raw_expandable_bottom_sheet.dart
> +    var checkedPersistentContentHeight = (widget.persistentContentHeight < contentHeight)
please keep the types

2021-06-08 06:17 UTC, BobanBaby commented
Done Please check it

2021-06-08 07:16 UTC, torbenkeller approved these changes

2021-06-08 07:16 UTC, merged

2021-06-08 07:16 UTC, torbenkeller commented
Thank you for contributing!

2021-06-15 14:00 UTC, torbenkeller commented
The new version is now published to pub.dev